### ISSUE TITLE
FBCTF 500's under docker swarm

### ISSUE THREAD

**Issue by denzuko** [AlexGaspar/docker-fbctf#10]
# Expected Results
Site up and operational

# Actual Results
Site returns 500

# Additional Details
 * ```
root@app:/var/log/hhvm# cat error.log
[Fri Aug 31 20:21:35 2018] [hphp] [54:7f1679bff700:1:000001] [] \nFatal error: Uncaught exception 'AsyncMysqlQueryException' with message 'Error executing AsyncMysql operation: Failed (mysql error: 1146: Table 'ctf2018.sessions' doesn't exist)' in /var/www/fbctf/src/SessionUtils.php:15\nStack trace:\n#0 /var/www/fbctf/src/SessionUtils.php(15): HH\\Asio\\join()\n#1 /var/www/fbctf/src/controllers/IndexController.php(440): SessionUtils::sessionStart()\n#2 /var/www/fbctf/src/controllers/IndexController.php(509): IndexController->renderMainNav()\n#3 /var/www/fbctf/src/controllers/Controller.php(12): IndexController->genRenderBody()\n#4 /var/www/fbctf/src/Router.php(67): Controller->genRender()\n#5 /var/www/fbctf/src/Router.php(18): Router::genRouteNormal()\n#6 /var/www/fbctf/src/index.php(7): Router::genRoute()\n#7 /var/www/fbctf/src/index.php(19): genInit()\n#8 {main}
```

# Expected Delta

 - Adjust bootstrap script to validate sql schemas are correct
 - If schema was not validated container dies with exit -1 and logs to stdout the results.

**Comment by denzuko** [comment]
Root cause:

Turns out that any change to MYSQL_DATABASE only creates two tables and not the rest of the schema which seems to be hardcoded to `fbctf`. Keeping `MYSQL_DATABASE` assigned to `fbctf` resolves the issue but does not correct for edge cases (ie if end user wished or required to run many different databases per their specification. For example ctf2018q1, defcon.2019, etc.).

**Comment by denzuko** [comment]
Looks like the issue is in the fbctf schema. I'll submit a pull request with them to resolve this.
